#!/usr/bin/env bash

app_url="https://crater.myterminal.me"

command_name=${1}
arguments=${@:2}

case ${command_name} in
    version | --version | -v)
        echo "Search not Implemented!"
        ;;

    help | --help | -h)
        echo "Help not Implemented!"
        ;;

    search)
        available_sources=$(/bin/bash -c "$(curl -s ${app_url}/list-sources)")
        echo ${available_sources}
        echo "Search not Implemented!"
        ;;

    list)
        echo "list not Implemented!"
        ;;

    install)
        echo "install not Implemented!"
        ;;

    uninstall)
        echo "uninstall not Implemented!"
        ;;

    update)
        echo "update not Implemented!"
        ;;

    *)
        echo "Please specify one of the following options:"
        echo " version / --version / -v"
        echo " help / --help / -h"
        echo " search"
        echo " list"
        echo " install"
        echo " uninstall"
        echo " update"
        ;;
esac
